export enum Routes {
  //App
  AUTH_NAVIGATOR = 'AUTH_NAVIGATOR',
  MOVIE_NAVIGATOR = 'MOVIE_NAVIGATOR',

  //AUTH
  SIGN_IN = 'SIGN_IN',
  SIGN_UP = 'SIGN_UP',

  //MOVIE
  MOVIE_LIST = 'MOVIE_LIST',
  MOVIE_DETAIL = 'MOVIE_DETAIL',
  MOVIE_FORM = 'MOVIE_FORM',
}
